import test from 'node:test';
import assert from 'node:assert/strict';
import {listingKey,uniqueListings,normalizeTrade,scopeTrades,summarize} from '../dist/core.mjs';
import {loadListings} from '../dist/data.mjs';
const now=Date.parse('2026-09-21T12:00:00Z');
const a={network:'eth',address:'0xAAA',symbol:'MEME'},b={network:'base',address:'0xAAA',symbol:'MEME'};
const event=(id,from,to,usd)=>({id,attributes:{from_token_address:from,to_token_address:to,volume_in_usd:String(usd),block_timestamp:new Date(now).toISOString()}});
test('Combined totals retain different chains and remove repeated pool events',()=>{const x=normalizeTrade(event('same-id','0xUSD',a.address,100),a.address,{network:a.network,name:'A',address:'pool'}),y=normalizeTrade(event('same-id',b.address,'0xUSD',40),b.address,{network:b.network,name:'B',address:'pool'});const combined=summarize(scopeTrades([x,x,y],[a,b]),60,now);assert.equal(combined.rows.length,2);assert.equal(combined.buy,100);assert.equal(combined.sell,40);assert.equal(combined.net,60);assert.equal(summarize(scopeTrades([x,y],[a,b],listingKey(b)),60,now).net,-40)});
test('Same-chain swaps between selected contracts are excluded only in combined view',()=>{const c={network:'eth',address:'0xBBB'};const e=event('swap',a.address,c.address,75);const rows=[normalizeTrade(e,a.address,{network:'eth'}),normalizeTrade(e,c.address,{network:'eth'})];assert.equal(scopeTrades(rows,[a,c]).length,0);assert.equal(scopeTrades(rows,[a,c],listingKey(a))[0].side,'sell');assert.equal(scopeTrades(rows,[a,c],listingKey(c))[0].side,'buy')});
test('Listing identity uses chain and contract, never ticker alone',()=>{assert.equal(uniqueListings([a,{...a,address:'0xaaa'},b]).length,2)});
function pool(network,address,base,quote){return {attributes:{address,name:'MEME / USD',reserve_in_usd:'500'},relationships:{base_token:{data:{id:`${network}_${base}`}},quote_token:{data:{id:`${network}_${quote}`}}}}}
test('Loader shares overlapping pools and reports individual listing failures',async()=>{const c={network:'eth',address:'0xBBB'},calls=[];const result=await loadListings([a,c,b],async path=>{calls.push(path);if(path.includes('/networks/base/'))throw new Error('Rate limited');if(path.includes('/tokens/'))return {data:[pool('eth','shared','0xAAA','0xBBB')]};return {data:[event('one',a.address,c.address,75)]}});assert.equal(calls.filter(p=>p.endsWith('/trades')).length,1);assert.deepEqual(result.listings.map(l=>l.status),['loaded','loaded','failed']);assert.equal(result.pools.length,1);assert.equal(result.trades.length,2);assert.equal(scopeTrades(result.trades,[a,c,b]).length,0)});
test('A failed pool is excluded without converting the listing to zero volume',async()=>{const result=await loadListings([a],async path=>{if(path.includes('/tokens/'))return {data:[pool('eth','p1',a.address,'USD'),pool('eth','p2',a.address,'USD')]};if(path.includes('/p2/'))throw new Error('unavailable');return {data:[event('one','USD',a.address,99)]}});assert.equal(result.listings[0].status,'partial');assert.equal(result.listings[0].successCount,1);assert.equal(result.pools.filter(p=>p.failed).length,1);assert.equal(summarize(scopeTrades(result.trades,[a]),60,now).buy,99)});
