import {STORY_SOURCES} from './dist/coin-context.mjs';
import http from 'node:http';
import {collect,readSnapshot,RETENTION_MS} from './worker/coin-collector.mjs';
const historyFile=path.resolve('.data/coins.json');
let collecting=false;
async function tick(){if(collecting)return;collecting=true;try{await collect(historyFile)}catch(error){console.error('Coin collector:',error.message)}finally{collecting=false}}

import {createMarketProxy} from './worker/market.mjs';
const market=createMarketProxy();
import {readFile} from 'node:fs/promises';
import path from 'node:path';
const base=path.resolve('dist');
http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/new-coins'){const snapshot=await readSnapshot(historyFile);snapshot.coins=snapshot.coins.filter(c=>c.firstSeen>Date.now()-RETENTION_MS);res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'}).end(JSON.stringify(snapshot));return}if(url.pathname.startsWith('/api/market/')){const response=await market(new Request(url,{method:req.method}));res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return}if(url.pathname.startsWith('/api/context/source/')){const source=STORY_SOURCES.find(s=>s.id===url.pathname.split('/').pop());if(!source){res.writeHead(404).end('Unknown story source');return}const response=await fetch('https://r.jina.ai/'+source.url,{signal:AbortSignal.timeout(28000)});res.writeHead(response.status,{'content-type':'text/plain; charset=utf-8'}).end((await response.text()).slice(0,60000));return}if(url.pathname==='/api/context/search'){const name=url.searchParams.get('name')?.trim()||'',symbol=url.searchParams.get('symbol')?.trim()||'',contract=url.searchParams.get('contract')?.trim()||'';if(!name||name.length>100||!symbol||symbol.length>32||!/^[A-Za-z0-9]{20,100}$/.test(contract)){res.writeHead(400).end('Invalid token context query');return}const query=url.searchParams.get('mode')==='contract'?`"${contract}"`:`"${name}" ${symbol} meme origin story`,target='https://r.jina.ai/http://html.duckduckgo.com/html/?'+new URLSearchParams({q:query});const response=await fetch(target,{headers:{accept:'text/plain'},signal:AbortSignal.timeout(20000)});if(!response.ok){res.writeHead(502).end('Context provider unavailable');return}res.writeHead(200,{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff'}).end((await response.text()).slice(0,60000));return}const filename=path.resolve(base,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!filename.startsWith(base+path.sep)){res.writeHead(403).end();return}const data=await readFile(filename);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.mjs': 'text/javascript'})[path.extname(filename)]||'application/octet-stream');res.end(data)}catch{res.writeHead(404).end('Not found')}}).listen(4173,'127.0.0.1',()=>{console.log('Local: http://127.0.0.1:4173');tick();setInterval(tick,300000).unref()});
